spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
     routes:
      - id: UPLOAD-SERVICE
        uri: lb://UPLOAD-SERVICE
        predicates:
        - Path=/api/fileupload/**
        filters:
        - StripPrefix=2
      - id: UPLOAD-CONSUMER-SERVICE
        uri: lb://UPLOAD-CONSUMER-SERVICE
        predicates:
        - Path=/api/fileuploadconsumer/**
        filters:
        - StripPrefix=2
